app/models.py
from . import db, login_manager
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


# 创建article和tag的多对多关系表
article_tag = db.Table('article_tag',
						db.Column('article_id', db.Integer, db.ForeignKey('articles.id')),
						db.Column('tag_id', db.Integer, db.ForeignKey('tags.id'))
						)



class Article(db.Model):
	__tablename__ = 'articles'
	id = db.Column(db.Integer, primary_key = True)
	titile = db.Column(db.String(64), unique = True)
	body = db.Column(db.Text)
	create_time = db.Column(db.DATETIME, default = datetime.utcnow())
	category_id = db.Column(db.Integer, db.ForeignKey('categorys.id'))
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
	tags = db.relationship('Tag', 
							secondary = article_tag,
							backref = db.backref('articles'))



class Category(db.Model):
	__tablename__ = 'categorys'
	id = db.Column(db.Integer, primary_key = True)
	name = db.Column(db.String(64), unique = True)
	articles = db.relationship('Article', backref = 'category')


class User(db.Model, UserMixin):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key = True)
	username = db.Column(db.String(64), unique = True)
	password_hash = db.Column(db.String(128))
	real_name = db.Column(db.String(64), unique = True)
	articles = db.relationship('Article', backref = 'user')

	@property
	def password(self):
		raise AttributeError(u'密码属性不正确')

	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))

class Tag(db.Model):
	__tablename__ = 'tags'
	id = db.Column(db.Integer, primary_key = True)
	tag_name = db.Column(db.String(64), unique = True)

app/admin/forms.py
from flask_wtf import FlaskForm as Form
from ..models import Category
from wtforms import StringField, SubmitField, PasswordField, TextAreaField
from wtforms.validators import Required, length, Regexp, EqualTo
from wtforms_sqlalchemy.fields import QuerySelectField


class LoginForm(Form):
	username = StringField(u'账号', validators = [Required(), length(6, 64)])
	password = PasswordField(u'密码', validators = [Required()])
	submit = SubmitField(u'登入')


class RegistrationForm(Form):
	username = StringField(u'用户名', validators = [Required(), length(6, 18), Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, u'用户名只允许字母'+u'用户名不允许特殊符号')])
	password = PasswordField(u'密码',
		validators = [Required(), EqualTo('password2', message = u'密码错误提示1')])
	password2 = PasswordField(u'重复密码', validators = [Required()])
	real_name = StringField(u'昵称')
	registerKey = StringField(u'注册码', validators = [Required()])
	submit = SubmitField(u'注册')


class PostArticleForm(Form):
	title = StringField(u'标题', validators = [Required(), length(3, 64)])
	body = TextAreaField(u'内容')
	category_id = QuerySelectField(u'分类', query_factory = lambda: Category.query.all(), get_pk = lambda a: str(a.id), get_label = lambda a: a.name)
	submit = SubmitField(u'发布')






class PostCategoryForm(Form):
	name = StringField(u'分类名', validators = [Required(), length(6, 64)])
	submit = SubmitField(u'发布')

app/__init__.py
# -*- coding=utf-8 -*-

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from config import config


db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'admin.login'
login_manager.login_message = u'请登入账号再进行下一步操作'


def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)

	db.init_app(app)
	bootstrap.init_app(app)
	login_manager.init_app(app)

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	from .admin import admin as admin_blueprint
	app.register_blueprint(admin_blueprint, url_prefix = '/admin')


	
	return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)


from . import views, errors

app/admin/views.py
from . import admin
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user, login_user, logout_user
from .forms import LoginForm, RegistrationForm, PostArticleForm, PostCategoryForm
from ..models import User, Article, Category
from .. import db


@admin.route('/')
def index():
	return render_template('admin/index.html')


@admin.route('/login', methods = ['GET', 'POST'])
def  login():
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username = form.username.data).first()
		if user is not None and user.verify_password(form.password.data):
			login_user(user)
			return redirect(request.args.get('next') or url_for('admin.index'))
		flash(u'用户密码不正确')
	return render_template('admin/login.html', form = form)


@admin.route('/register', methods = ['GET', 'POST'])
def register():
	register_key = 'zhucema'
	form = RegistrationForm()
	if form.validate_on_submit():
		if form.registerKey.data != register_key:
			flash(u'注册码不符，请返回重试.')
			return redirect(url_for(admin.register))
		else:
			if form.password.data != form.password2.data:
				flash(u'两次输入密码不一')
				return redirect(url_for('admin.register'))
			else:
				user = User(username = form.username.data, 
							password = form.password.data, 
							real_name = form.real_name.data)
				db.session.add(user)
				flash(u'您已注册成功')
				return redirect(url_for('admin.login'))
	return render_template('admin/register.html', form = form)


@admin.route('/logout')
@login_required
def logout():
	logout_user()
	flash(u'您已经登出了系统')
	return redirect(url_for('main.index'))


@admin.route('/article', methods = ['GET', 'POST'])
@login_required
def article():
	form = PostArticleForm()
	alist = Article.query.all()
	if form.validate_on_submit():
		article = Article(title = form.title.data,
						  body = form.body.data,
						  category_id = str(form.category_id.data.id),
						  user_id = current_user.id)
		db.session.add(article)
		flash(u'文章添加成功')
		redirect(url_for('admin.index'))
	return render_template('admin/article.html', form = form, list = alist)


@admin.route('/article/del', methods = ['GET'])
@login_required
def article_del():
	if request.args.get('id') is not None and request.args.get('a') == 'del':
		x = Article.query.filter_by(id = request.args.get('id')).first()
		if x is not None:
			db.session.delete(x)
			db.session.commit()
			flash(u'已经删除' + x.title)
			return redirect(url_for('admin.article'))
		flash(u'请检查输入')
		return redirect(url_for('admin.article'))


@admin.route('/category', methods = ['GET', 'POST'])
def category():
	clist = Category.query.all()
	form = PostCategoryForm()
	if form.validate_on_submit():
		category = Category(name = form.name.data)
		db.session.add(category)
		flash(u'分类添加成功')
		return redirect(url_for('admin.index'))
	return render_template('admin/category.html', form = form, list = clist)


@admin.route('/category/del', methods = ['GET'])
@login_required
def category_del():
	if request.args.get('id') is not None and request.args.get('a') == 'del':
		x = Category.query.filter_by(id = request.args.get('id')).first()
		if x is not None:
			db.session.delete(x)
			db.session.commit()
			flash(u'已经删除分类' + x.name)
			return redirect(url_for('admin.category'))
		flash(u'请检查输入')
		return redirect(url_for('admin.category'))

	

app/main/__init__.py
# -*- coding=utf-8 -*-

from flask import Blueprint


main = Blueprint('main', __name__)


from . import views, errors

app/main/views.py
# -*- coding=utf-8 -*-

from . import main

@main.route('/')
def index():
	return 'Hello World'

app/views.py
# -*- coding=utf-8 -*-

from . import main

@main.route('/')
def index():
	return 'Hello World'

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %} Flask-Blog{% endblock %}
{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Blog</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">首页</a></li>
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('admin.index') }}">后台首页</a></li>
                        <li><a href="{{ url_for('admin.article') }}">文章</a></li>
                        <li><a href="{{ url_for('admin.category') }}">分类</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('admin.logout') }}">登出</a></li>
                    {% else %}
                        <li><a href="{{ url_for('admin.register') }}">注册</a></li>
                        <li><a href="{{ url_for('admin.login') }}">登入</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}
        {% endblock %}
    </div>
{% endblock %}